-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2016-06-26 05:17:22.832

CREATE DATABASE BD_EMERGENCIA
GO

USE BD_EMERGENCIA
GO
-- tables
-- Table: CIVIL
CREATE TABLE CIVIL (
    CIV_ID int  NOT NULL IDENTITY(1, 1),
    CIV_NOMBRE nvarchar(50)  NULL,
    CIV_APELLIDO_PATERNO nvarchar(50)  NULL,
    CIV_APELLIDO_MATERNO nvarchar(50)  NULL,
    CIV_TELEFONO nvarchar(20)  NULL,
    CIV_DOCUMENTO nvarchar(12)  NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    FECHA_REGISTRO datetime  NULL DEFAULT getdate(),
    FECHA_MODIFICACION datetime  NULL,
    CONSTRAINT UN_CIV_DOCUMENTO UNIQUE (CIV_DOCUMENTO),
    CONSTRAINT CIVIL_pk PRIMARY KEY  (CIV_ID)
);

-- Table: COMISARIA
CREATE TABLE COMISARIA (
    COM_ID int  NOT NULL IDENTITY(1, 1),
    COM_NOMBRE nvarchar(100)  NOT NULL,
    COM_DIRECCION nvarchar(100)  NOT NULL,
    DIS_ID int  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    CONSTRAINT COMISARIA_pk PRIMARY KEY  (COM_ID)
);

-- Table: DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    DEP_ID int  NOT NULL IDENTITY(1, 1),
    DEP_DESCRIPCION nvarchar(50)  NOT NULL,
    CONSTRAINT DEPARTAMENTO_pk PRIMARY KEY  (DEP_ID)
);

-- Table: DISTRITO
CREATE TABLE DISTRITO (
    DIS_ID int  NOT NULL IDENTITY(1, 1),
    DIS_DESCRIPCION nvarchar(50)  NOT NULL,
    PRO_ID int  NOT NULL,
    CONSTRAINT DISTRITO_pk PRIMARY KEY  (DIS_ID)
);

-- Table: EMERGENCIA
CREATE TABLE EMERGENCIA (
    EME_ID int  NOT NULL IDENTITY(1, 1),
    NEM_ID int  NOT NULL,
    LLA_ID int  NOT NULL,
    TEM_ID int  NOT NULL,
    DIS_ID int  NOT NULL,
    EME_DIR nvarchar(100)  NOT NULL,
    EME_OBSERVACION nvarchar(500)  NOT NULL,
    EME_FECHA datetime  NULL DEFAULT getdate(),
    EME_HORA_INICIO time(0)  NULL,
    EME_HORA_FIN time(0)  NULL,
    CONSTRAINT EMERGENCIA_pk PRIMARY KEY  (EME_ID)
);

-- Table: EQUIPO_EMERGENCIA
CREATE TABLE EQUIPO_EMERGENCIA (
    EEM_ID int  NOT NULL IDENTITY(1, 1),
    REC_ID int  NOT NULL,
    EME_ID int  NOT NULL,
    CONSTRAINT EQUIPO_EMERGENCIA_pk PRIMARY KEY  (EEM_ID)
);

-- Table: ESTADO
CREATE TABLE ESTADO (
    EST_ID int  NOT NULL IDENTITY(1, 1),
    EST_DESCRIPCION nvarchar(20)  NOT NULL,
    CONSTRAINT ESTADO_pk PRIMARY KEY  (EST_ID)
);

-- Table: ESTADO_PARTE
CREATE TABLE ESTADO_PARTE (
    EPA_ID int  NOT NULL IDENTITY(1, 1),
    EPA_DESCRIPCION nvarchar(50)  NOT NULL,
    CONSTRAINT ESTADO_PARTE_pk PRIMARY KEY  (EPA_ID)
);

-- Table: GRADO_RECURSO
CREATE TABLE GRADO_RECURSO (
    GRE_ID int  NOT NULL IDENTITY(1, 1),
    GRE_DESCRIPCION nvarchar(50)  NOT NULL,
    GRE_JERARQUIA int  NOT NULL,
    CONSTRAINT GRADO_RECURSO_pk PRIMARY KEY  (GRE_ID)
);

-- Table: LLAMADA
CREATE TABLE LLAMADA (
    LLA_ID int  NOT NULL IDENTITY(1, 1),
    LLA_OBSERVACION nvarchar(500)  NULL,
    LLA_FECHA datetime  NOT NULL DEFAULT getdate(),
    LLA_ESTADO bit  NULL DEFAULT 1,
    LLA_TELEFONO nvarchar(20)  NOT NULL,
    TTE_ID int  NOT NULL,
    CIV_ID int  NOT NULL,
    OPE_ID int  NOT NULL,
    LLA_HORA_INICIO time(0)  NULL,
    LLA_HORA_FIN time(0)  NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    CONSTRAINT LLAMADA_pk PRIMARY KEY  (LLA_ID)
);

-- Table: NIVEL_EMERGENCIA
CREATE TABLE NIVEL_EMERGENCIA (
    NEM_ID int  NOT NULL IDENTITY(1, 1),
    NEM_DESCRIPCION nvarchar(50)  NOT NULL,
    CONSTRAINT NIVEL_EMERGENCIA_pk PRIMARY KEY  (NEM_ID)
);

-- Table: OPERADOR
CREATE TABLE OPERADOR (
    OPE_ID int  NOT NULL IDENTITY(1, 1),
    TUR_ID int  NOT NULL,
    PER_ID int  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    FECHA_CREACION datetime  NULL DEFAULT GETDATE(),
    FECHA_MODIFICACION datetime  NULL,
    CONSTRAINT OPERADOR_pk PRIMARY KEY  (OPE_ID)
);

-- Table: PARTE
CREATE TABLE PARTE (
    PAR_ID int  NOT NULL IDENTITY(1, 1),
    EME_ID int  NOT NULL,
    EPA_ID int  NOT NULL,
    REC_ID int  NOT NULL,
    PAR_OBSERVACION nvarchar(500)  NOT NULL,
    PAR_FECHA datetime  NULL DEFAULT getdate(),
    CONSTRAINT PARTE_pk PRIMARY KEY  (PAR_ID)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    PER_ID int  NOT NULL IDENTITY(1, 1),
    USU_ID int  NOT NULL,
    TPE_ID int  NOT NULL,
    PER_NOMBRE nvarchar(50)  NOT NULL,
    PER_APELLIDO_PATERNO nvarchar(50)  NOT NULL,
    PER_APELLIDO_MATERNO nvarchar(50)  NOT NULL,
    PER_FECHA_NACIMIENTO datetime  NOT NULL,
    PER_DNI CHAR(8)  NOT NULL,
    PER_DIRECCION nvarchar(100)  NOT NULL,
    PER_CORREO nvarchar(100)  NULL,
    PER_TELEFONO nvarchar(20)  NULL,
    PER_GENERO char(1)  NOT NULL,
    PER_ESTADO_CIVIL nvarchar(15)  NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    FECHA_CREACION datetime  NULL DEFAULT getdate(),
    FECHA_MODIFICACION datetime  NULL DEFAULT getdate(),
    CONSTRAINT UN_PER_DNI UNIQUE (PER_DNI),
    CONSTRAINT PERSONA_pk PRIMARY KEY  (PER_ID)
);

-- Table: PROVINCIA
CREATE TABLE PROVINCIA (
    PRO_ID int  NOT NULL IDENTITY(1, 1),
    PRO_DESCRIPCION nvarchar(50)  NOT NULL,
    DEP_ID int  NOT NULL,
    CONSTRAINT PROVINCIA_pk PRIMARY KEY  (PRO_ID)
);

-- Table: RECURSO
CREATE TABLE RECURSO (
    REC_ID int  NOT NULL IDENTITY(1, 1),
    PER_ID int  NOT NULL,
    GRE_ID int  NOT NULL,
    TUR_ID int  NOT NULL,
    COM_ID int  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    FECHA_CREACION datetime  NULL DEFAULT GETDATE(),
    FECHA_MODIFICACION datetime  NULL,
    CONSTRAINT RECURSO_pk PRIMARY KEY  (REC_ID)
);

-- Table: RECURSO_ESTADO
CREATE TABLE RECURSO_ESTADO (
    REE_ID int  NOT NULL IDENTITY(1, 1),
    REC_ID int  NOT NULL,
    EST_ID int  NOT NULL,
    REE_FECHA datetime  NULL DEFAULT GETDATE(),
    CONSTRAINT RECURSO_ESTADO_pk PRIMARY KEY  (REE_ID)
);

-- Table: ROL
CREATE TABLE ROL (
    ROL_ID int  NOT NULL IDENTITY(1, 1),
    ROL_DESCRIPCION varchar(30)  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    CONSTRAINT ROL_pk PRIMARY KEY  (ROL_ID)
);

-- Table: SECTOR
CREATE TABLE SECTOR (
    SEC_ID int  NOT NULL IDENTITY(1, 1),
    SEC_CORDENADA_X real  NULL,
    SEC_CORDENADA_Y real  NULL,
    COM_ID int  NOT NULL,
    DIS_ID int  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    CONSTRAINT SECTOR_pk PRIMARY KEY  (SEC_ID)
);

-- Table: TIPO_EMERGENCIA
CREATE TABLE TIPO_EMERGENCIA (
    TEM_ID int  NOT NULL IDENTITY(1, 1),
    TEM_DESCRIPCION nvarchar(50)  NOT NULL,
    CONSTRAINT TIPO_EMERGENCIA_pk PRIMARY KEY  (TEM_ID)
);

-- Table: TIPO_PERSONAL
CREATE TABLE TIPO_PERSONAL (
    TPE_ID int  NOT NULL IDENTITY(1, 1),
    TPE_DESCRIPCION nvarchar(50)  NOT NULL,
    CONSTRAINT TIPO_PERSONAL_pk PRIMARY KEY  (TPE_ID)
);

-- Table: TIPO_TERMINAL
CREATE TABLE TIPO_TERMINAL (
    TTE_ID int  NOT NULL IDENTITY(1, 1),
    TTE_DESCRIPCION varchar(30)  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    CONSTRAINT TIPO_TERMINAL_pk PRIMARY KEY  (TTE_ID)
);

-- Table: TURNO
CREATE TABLE TURNO (
    TUR_ID int  NOT NULL IDENTITY(1, 1),
    TUR_DESCRIPCION nvarchar(20)  NOT NULL,
    TUR_RANGO nvarchar(20)  NOT NULL,
    TUR_HORA_INICIAL time(0)  NOT NULL,
    TUR_HORA_FINAL time(0)  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    CONSTRAINT TURNO_pk PRIMARY KEY  (TUR_ID)
);

-- Table: USUARIO
CREATE TABLE USUARIO (
    USU_ID int  NOT NULL IDENTITY(1, 1),
    ROL_ID int  NOT NULL,
    USU_NOMBRE nvarchar(50)  NOT NULL,
    USU_CLAVE nvarchar(50)  NOT NULL,
    ESTADO_REGISTRO bit  NULL DEFAULT 1,
    FECHA_CREACION datetime  NULL DEFAULT getdate(),
    FECHA_MODIFICACION datetime  NULL DEFAULT getdate(),
    CONSTRAINT USUARIO_pk PRIMARY KEY  (USU_ID)
);

-- foreign keys
-- Reference: COMISARIA_DISTRITO (table: COMISARIA)
ALTER TABLE COMISARIA ADD CONSTRAINT COMISARIA_DISTRITO
    FOREIGN KEY (DIS_ID)
    REFERENCES DISTRITO (DIS_ID);

-- Reference: DISTRITO_PROVINCIA (table: DISTRITO)
ALTER TABLE DISTRITO ADD CONSTRAINT DISTRITO_PROVINCIA
    FOREIGN KEY (PRO_ID)
    REFERENCES PROVINCIA (PRO_ID);

-- Reference: EMERGENCIA_DISTRITO (table: EMERGENCIA)
ALTER TABLE EMERGENCIA ADD CONSTRAINT EMERGENCIA_DISTRITO
    FOREIGN KEY (DIS_ID)
    REFERENCES DISTRITO (DIS_ID);

-- Reference: EMERGENCIA_LLAMADA (table: EMERGENCIA)
ALTER TABLE EMERGENCIA ADD CONSTRAINT EMERGENCIA_LLAMADA
    FOREIGN KEY (LLA_ID)
    REFERENCES LLAMADA (LLA_ID);

-- Reference: EMERGENCIA_NIVEL_EMERGENCIA (table: EMERGENCIA)
ALTER TABLE EMERGENCIA ADD CONSTRAINT EMERGENCIA_NIVEL_EMERGENCIA
    FOREIGN KEY (NEM_ID)
    REFERENCES NIVEL_EMERGENCIA (NEM_ID);

-- Reference: EMERGENCIA_TIPO_EMERGENCIA (table: EMERGENCIA)
ALTER TABLE EMERGENCIA ADD CONSTRAINT EMERGENCIA_TIPO_EMERGENCIA
    FOREIGN KEY (TEM_ID)
    REFERENCES TIPO_EMERGENCIA (TEM_ID);

-- Reference: EQUIPO_EMERGENCIA_EMERGENCIA (table: EQUIPO_EMERGENCIA)
ALTER TABLE EQUIPO_EMERGENCIA ADD CONSTRAINT EQUIPO_EMERGENCIA_EMERGENCIA
    FOREIGN KEY (EME_ID)
    REFERENCES EMERGENCIA (EME_ID);

-- Reference: EQUIPO_EMERGENCIA_RECURSO (table: EQUIPO_EMERGENCIA)
ALTER TABLE EQUIPO_EMERGENCIA ADD CONSTRAINT EQUIPO_EMERGENCIA_RECURSO
    FOREIGN KEY (REC_ID)
    REFERENCES RECURSO (REC_ID);

-- Reference: LLAMADA_CIVIL (table: LLAMADA)
ALTER TABLE LLAMADA ADD CONSTRAINT LLAMADA_CIVIL
    FOREIGN KEY (CIV_ID)
    REFERENCES CIVIL (CIV_ID);

-- Reference: LLAMADA_OPERADOR (table: LLAMADA)
ALTER TABLE LLAMADA ADD CONSTRAINT LLAMADA_OPERADOR
    FOREIGN KEY (OPE_ID)
    REFERENCES OPERADOR (OPE_ID);

-- Reference: LLAMADA_TipoTerminal (table: LLAMADA)
ALTER TABLE LLAMADA ADD CONSTRAINT LLAMADA_TipoTerminal
    FOREIGN KEY (TTE_ID)
    REFERENCES TIPO_TERMINAL (TTE_ID);

-- Reference: OPERADOR_PERSONA (table: OPERADOR)
ALTER TABLE OPERADOR ADD CONSTRAINT OPERADOR_PERSONA
    FOREIGN KEY (PER_ID)
    REFERENCES PERSONA (PER_ID);

-- Reference: OPERADOR_TURNO (table: OPERADOR)
ALTER TABLE OPERADOR ADD CONSTRAINT OPERADOR_TURNO
    FOREIGN KEY (TUR_ID)
    REFERENCES TURNO (TUR_ID);

-- Reference: PARTE_EMERGENCIA (table: PARTE)
ALTER TABLE PARTE ADD CONSTRAINT PARTE_EMERGENCIA
    FOREIGN KEY (EME_ID)
    REFERENCES EMERGENCIA (EME_ID);

-- Reference: PARTE_EstadoParte (table: PARTE)
ALTER TABLE PARTE ADD CONSTRAINT PARTE_EstadoParte
    FOREIGN KEY (EPA_ID)
    REFERENCES ESTADO_PARTE (EPA_ID);

-- Reference: PARTE_RECURSO (table: PARTE)
ALTER TABLE PARTE ADD CONSTRAINT PARTE_RECURSO
    FOREIGN KEY (REC_ID)
    REFERENCES RECURSO (REC_ID);

-- Reference: PERSONA_TIPO_PERSONAL (table: PERSONA)
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_TIPO_PERSONAL
    FOREIGN KEY (TPE_ID)
    REFERENCES TIPO_PERSONAL (TPE_ID);

-- Reference: PERSONA_USUARIO (table: PERSONA)
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_USUARIO
    FOREIGN KEY (USU_ID)
    REFERENCES USUARIO (USU_ID);

-- Reference: PROVINCIA_DEPARTAMENTO (table: PROVINCIA)
ALTER TABLE PROVINCIA ADD CONSTRAINT PROVINCIA_DEPARTAMENTO
    FOREIGN KEY (DEP_ID)
    REFERENCES DEPARTAMENTO (DEP_ID);

-- Reference: RECURSO_COMISARIA (table: RECURSO)
ALTER TABLE RECURSO ADD CONSTRAINT RECURSO_COMISARIA
    FOREIGN KEY (COM_ID)
    REFERENCES COMISARIA (COM_ID);

-- Reference: RECURSO_ESTADO_ESTADO (table: RECURSO_ESTADO)
ALTER TABLE RECURSO_ESTADO ADD CONSTRAINT RECURSO_ESTADO_ESTADO
    FOREIGN KEY (EST_ID)
    REFERENCES ESTADO (EST_ID);

-- Reference: RECURSO_ESTADO_RECURSO (table: RECURSO_ESTADO)
ALTER TABLE RECURSO_ESTADO ADD CONSTRAINT RECURSO_ESTADO_RECURSO
    FOREIGN KEY (REC_ID)
    REFERENCES RECURSO (REC_ID);

-- Reference: RECURSO_GRADO_RECURSO (table: RECURSO)
ALTER TABLE RECURSO ADD CONSTRAINT RECURSO_GRADO_RECURSO
    FOREIGN KEY (GRE_ID)
    REFERENCES GRADO_RECURSO (GRE_ID);

-- Reference: RECURSO_PERSONA (table: RECURSO)
ALTER TABLE RECURSO ADD CONSTRAINT RECURSO_PERSONA
    FOREIGN KEY (PER_ID)
    REFERENCES PERSONA (PER_ID);

-- Reference: RECURSO_TURNO (table: RECURSO)
ALTER TABLE RECURSO ADD CONSTRAINT RECURSO_TURNO
    FOREIGN KEY (TUR_ID)
    REFERENCES TURNO (TUR_ID);

-- Reference: SECTOR_COMISARIA (table: SECTOR)
ALTER TABLE SECTOR ADD CONSTRAINT SECTOR_COMISARIA
    FOREIGN KEY (COM_ID)
    REFERENCES COMISARIA (COM_ID);

-- Reference: SECTOR_DISTRITO (table: SECTOR)
ALTER TABLE SECTOR ADD CONSTRAINT SECTOR_DISTRITO
    FOREIGN KEY (DIS_ID)
    REFERENCES DISTRITO (DIS_ID);

-- Reference: USUARIO_ROL (table: USUARIO)
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_ROL
    FOREIGN KEY (ROL_ID)
    REFERENCES ROL (ROL_ID);

-- End of file.
